#############################################################################
# Makefile for building: qimagefuzz
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  qimage.pro
# Template: app
# Command: /usr/local/Qt-5.5.0/bin/qmake -o Makefile qimage.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            ?= gcc
CXX           ?= g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Qt-5.5.0/include -I/usr/local/Qt-5.5.0/include/QtGui -I/usr/local/Qt-5.5.0/include/QtCore -I. -I/usr/local/Qt-5.5.0/mkspecs/linux-g++
QMAKE         = /usr/local/Qt-5.5.0/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qimagefuzz1.0.0
DISTDIR = /home/michael/Programming/qimage-fuzz/.tmp/qimagefuzz1.0.0
LINK          = g++
LFLAGS        =
LIBS          = $(SUBLIBS) -L/usr/local/Qt-5.5.0/lib -L/usr/local/Qt-5.5.0/plugins/platforms -lqxcb -lQt5XcbQpa -lX11 -lX11-xcb -lXi -lSM -lICE -lxcb -L/home/michael/Programming/Telegram/Libraries/QtStatic/qtbase/src/plugins/platforms/xcb/xcb-static -lxcb-static -lQt5PlatformSupport -lfontconfig -lfreetype -lQt5DBus -L/usr/local/Qt-5.5.0/plugins/imageformats -lqdds -lqicns -lqico -lqjp2 -lqmng -lqtga -lqtiff -lqwbmp -lqwebp -lQt5Gui -lpng -lqtharfbuzzng -lQt5Core -lz -lqtpcre -lm -ldl -pthread -lgthread-2.0 -lglib-2.0 -lrt -lpthread
AR            = ar cqs
RANLIB        =
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qimage.cpp \
		qimagefuzz_plugin_import.cpp
OBJECTS       = qimage.o \
		qimagefuzz_plugin_import.o
DIST          = /usr/local/Qt-5.5.0/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.5.0/mkspecs/common/unix.conf \
		/usr/local/Qt-5.5.0/mkspecs/common/linux.conf \
		/usr/local/Qt-5.5.0/mkspecs/common/sanitize.conf \
		/usr/local/Qt-5.5.0/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.5.0/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.5.0/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.5.0/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.5.0/mkspecs/qconfig.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_fcitxplatforminputcontextplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qdds.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qgtk2.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qicns.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qico.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qjp2.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qminimal.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qmng.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qnmbearer.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qsqlite.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qtga.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qtiff.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qwbmp.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qwebp.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qxcb.pri \
		/usr/local/Qt-5.5.0/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.5.0/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.5.0/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/qt.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/resources.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/moc.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/lex.prf \
		qimage.pro  qimage.cpp \
		qimagefuzz_plugin_import.cpp
QMAKE_TARGET  = qimagefuzz
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = qimagefuzz


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): /usr/local/Qt-5.5.0/lib/libQt5Gui.a /usr/local/Qt-5.5.0/lib/libQt5Core.a $(OBJECTS)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qimage.pro /usr/local/Qt-5.5.0/mkspecs/linux-g++/qmake.conf /usr/local/Qt-5.5.0/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.5.0/mkspecs/common/unix.conf \
		/usr/local/Qt-5.5.0/mkspecs/common/linux.conf \
		/usr/local/Qt-5.5.0/mkspecs/common/sanitize.conf \
		/usr/local/Qt-5.5.0/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.5.0/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.5.0/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.5.0/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.5.0/mkspecs/qconfig.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_fcitxplatforminputcontextplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qdds.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qgtk2.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qicns.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qico.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qjp2.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qminimal.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qmng.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qnmbearer.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qsqlite.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qtga.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qtiff.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qwbmp.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qwebp.pri \
		/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qxcb.pri \
		/usr/local/Qt-5.5.0/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.5.0/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.5.0/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/qt.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/resources.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/moc.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.5.0/mkspecs/features/lex.prf \
		qimage.pro \
		/usr/local/Qt-5.5.0/lib/libQt5Gui.prl \
		/usr/local/Qt-5.5.0/lib/libQt5Core.prl \
		/usr/local/Qt-5.5.0/plugins/platforms/libqxcb.prl \
		/usr/local/Qt-5.5.0/plugins/imageformats/libqdds.prl \
		/usr/local/Qt-5.5.0/plugins/imageformats/libqicns.prl \
		/usr/local/Qt-5.5.0/plugins/imageformats/libqico.prl \
		/usr/local/Qt-5.5.0/plugins/imageformats/libqjp2.prl \
		/usr/local/Qt-5.5.0/plugins/imageformats/libqmng.prl \
		/usr/local/Qt-5.5.0/plugins/imageformats/libqtga.prl \
		/usr/local/Qt-5.5.0/plugins/imageformats/libqtiff.prl \
		/usr/local/Qt-5.5.0/plugins/imageformats/libqwbmp.prl \
		/usr/local/Qt-5.5.0/plugins/imageformats/libqwebp.prl
	$(QMAKE) -o Makefile qimage.pro
/usr/local/Qt-5.5.0/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.5.0/mkspecs/common/unix.conf:
/usr/local/Qt-5.5.0/mkspecs/common/linux.conf:
/usr/local/Qt-5.5.0/mkspecs/common/sanitize.conf:
/usr/local/Qt-5.5.0/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.5.0/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt-5.5.0/mkspecs/common/g++-base.conf:
/usr/local/Qt-5.5.0/mkspecs/common/g++-unix.conf:
/usr/local/Qt-5.5.0/mkspecs/qconfig.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_fcitxplatforminputcontextplugin.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qconnmanbearer.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qdds.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qgtk2.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qicns.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qico.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qjp2.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qlinuxfb.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qminimal.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qmng.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qnmbearer.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qoffscreen.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qsqlite.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qtga.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qtiff.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qwbmp.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qwebp.pri:
/usr/local/Qt-5.5.0/mkspecs/modules/qt_plugin_qxcb.pri:
/usr/local/Qt-5.5.0/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.5.0/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.5.0/mkspecs/linux-g++/qmake.conf:
/usr/local/Qt-5.5.0/mkspecs/features/spec_post.prf:
/usr/local/Qt-5.5.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.5.0/mkspecs/features/default_pre.prf:
/usr/local/Qt-5.5.0/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.5.0/mkspecs/features/default_post.prf:
/usr/local/Qt-5.5.0/mkspecs/features/qt.prf:
/usr/local/Qt-5.5.0/mkspecs/features/resources.prf:
/usr/local/Qt-5.5.0/mkspecs/features/moc.prf:
/usr/local/Qt-5.5.0/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.5.0/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.5.0/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.5.0/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.5.0/mkspecs/features/yacc.prf:
/usr/local/Qt-5.5.0/mkspecs/features/lex.prf:
qimage.pro:
/usr/local/Qt-5.5.0/lib/libQt5Gui.prl:
/usr/local/Qt-5.5.0/lib/libQt5Core.prl:
/usr/local/Qt-5.5.0/plugins/platforms/libqxcb.prl:
/usr/local/Qt-5.5.0/plugins/imageformats/libqdds.prl:
/usr/local/Qt-5.5.0/plugins/imageformats/libqicns.prl:
/usr/local/Qt-5.5.0/plugins/imageformats/libqico.prl:
/usr/local/Qt-5.5.0/plugins/imageformats/libqjp2.prl:
/usr/local/Qt-5.5.0/plugins/imageformats/libqmng.prl:
/usr/local/Qt-5.5.0/plugins/imageformats/libqtga.prl:
/usr/local/Qt-5.5.0/plugins/imageformats/libqtiff.prl:
/usr/local/Qt-5.5.0/plugins/imageformats/libqwbmp.prl:
/usr/local/Qt-5.5.0/plugins/imageformats/libqwebp.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qimage.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qimage.cpp qimagefuzz_plugin_import.cpp $(DISTDIR)/


clean: compiler_clean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean
	-$(DEL_FILE) $(TARGET)
	-$(DEL_FILE) /home/michael/Programming/qimage-fuzz/qimagefuzz_plugin_import.cpp
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean:

####### Compile

qimage.o: qimage.cpp /usr/local/Qt-5.5.0/include/QtCore/QIODevice \
		/usr/local/Qt-5.5.0/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5.0/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.0/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.0/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.0/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.0/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.0/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.0/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.0/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.0/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.0/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.0/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.0/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.0/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.0/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.0/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.0/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.0/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.0/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.0/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.0/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.0/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.0/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.0/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.0/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.0/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.0/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.0/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.0/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.0/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.0/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.0/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.0/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.0/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.0/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.0/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.0/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.0/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.0/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.0/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.0/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.0/include/QtGui/QImage \
		/usr/local/Qt-5.5.0/include/QtGui/qimage.h \
		/usr/local/Qt-5.5.0/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5.0/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5.0/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5.0/include/QtCore/qvector.h \
		/usr/local/Qt-5.5.0/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5.0/include/QtCore/qrect.h \
		/usr/local/Qt-5.5.0/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5.0/include/QtCore/qsize.h \
		/usr/local/Qt-5.5.0/include/QtGui/qregion.h \
		/usr/local/Qt-5.5.0/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5.0/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5.0/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5.0/include/QtCore/qpair.h \
		/usr/local/Qt-5.5.0/include/QtCore/qline.h \
		/usr/local/Qt-5.5.0/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5.0/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5.0/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5.0/include/QtGui/qpixelformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qimage.o qimage.cpp

qimagefuzz_plugin_import.o: qimagefuzz_plugin_import.cpp /usr/local/Qt-5.5.0/include/QtCore/QtPlugin \
		/usr/local/Qt-5.5.0/include/QtCore/qplugin.h \
		/usr/local/Qt-5.5.0/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.0/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.0/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.0/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.0/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.0/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.0/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.0/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.0/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.0/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.0/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.0/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.0/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.0/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.0/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.0/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.0/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.0/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.0/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.0/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.0/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.0/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.0/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.0/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.0/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.0/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.0/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.0/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.0/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.0/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.0/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.0/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.0/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.0/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.0/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.0/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.0/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.0/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.0/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.0/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.0/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.0/include/QtCore/qpointer.h \
		/usr/local/Qt-5.5.0/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5.0/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5.0/include/QtCore/qhash.h \
		/usr/local/Qt-5.5.0/include/QtCore/qpair.h \
		/usr/local/Qt-5.5.0/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5.0/include/QtCore/qjsonobject.h \
		/usr/local/Qt-5.5.0/include/QtCore/qjsonvalue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qimagefuzz_plugin_import.o qimagefuzz_plugin_import.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

